package com.example.pamo_pz

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a financial goal in the application.
 *
 * @property name The name of the goal.
 * @property description The description of the goal.
 * @property value The current value of the goal.
 * @property target The target value to be achieved.
 * @property id The unique identifier of the goal. It is autogenerated by the database.
 */
@Entity(tableName = "goals")
data class Goal(
    val name: String,
    val description: String,
    val value: Double,
    val monthlyDeposit: Double,
    val target: Double,
    @PrimaryKey(autoGenerate = true) val id: Int = 0
)