package com.example.pamo_pz

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a transaction.
 *
 * @property name The name of the transaction.
 * @property month The month when the transaction occurred.
 * @property category The category of the transaction (e.g., groceries, education).
 * @property amount The amount of money involved in the transaction.
 * @property isIncome Indicates whether the transaction is an income (true) or an expense (false). Default is false.
 * @property id The unique identifier for the transaction. Auto-generated by the database.
 */

@Entity(tableName = "transactions")
data class Transaction(
    val name: String,
    val month: String,
    val category: String,
    val amount: Double,
    val isIncome: Boolean = false,
    @PrimaryKey(autoGenerate = true) val id: Int = 0
)